name: Release
on:
  push:
    tags:
      - v*
jobs:
  build-publish:
    name: 'Build & Publish'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup NuGet
        run: |
          dotnet nuget update source github --store-password-in-clear-text --username SeanLatimer --password ${{ secrets.GITHUB_TOKEN }}
          dotnet nuget enable source github

#      - name: Setup Verlite
#        run: |
#          dotnet tool install --global Verlite.CLI --version "2.1.0"
#          verlite . --auto-fetch --verbosity verbatim

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack -o artifacts --configuration Release --no-restore

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            artifacts/*
 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.nupkg
 
      - name: Publish Nuget
        run: |
          dotnet nuget push 'artifacts/*.nupkg' -k ${NUGETORG_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
          dotnet nuget push 'artifacts/*.nupkg' -k ${GITHUB_TOKEN} -s github --skip-duplicate --no-symbols
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGETORG_TOKEN: ${{ secrets.NUGETORG_TOKEN }}
